package net.ddns.tiojack.htte.service;

import com.google.common.collect.ImmutableMap;
import lombok.RequiredArgsConstructor;
import net.ddns.tiojack.htte.model.LineMatch;
import net.ddns.tiojack.htte.model.MatchDetail;
import net.ddns.tiojack.htte.model.Player;
import net.ddns.tiojack.htte.model.Position;
import net.ddns.tiojack.htte.model.Ratings;
import net.ddns.tiojack.htte.model.Skill;
import net.ddns.tiojack.htte.model.Specialty;
import net.ddns.tiojack.htte.model.ZoneMatch;
import org.springframework.stereotype.Service;

import java.util.Arrays;
import java.util.Map;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class PlayerRatingService {

    public Map<Position, Ratings> getRatings(final Player player, final MatchDetail matchDetail) {
        return Arrays.stream(Position.values()).collect(Collectors.toMap(position -> position, position -> Ratings.builder()
                .rightDefense(this.getCoefficientByPositionAndZone(player, position, ZoneMatch.RIGHT_DEFENSE, matchDetail))
                .centralDefense(this.getCoefficientByPositionAndZone(player, position, ZoneMatch.CENTRAL_DEFENSE, matchDetail))
                .leftDefense(this.getCoefficientByPositionAndZone(player, position, ZoneMatch.LEFT_DEFENSE, matchDetail))
                .midfield(this.getCoefficientByPositionAndZone(player, position, ZoneMatch.MIDFIELD, matchDetail))
                .rightAttack(this.getCoefficientByPositionAndZone(player, position, ZoneMatch.RIGHT_ATTACK, matchDetail))
                .centralAttack(this.getCoefficientByPositionAndZone(player, position, ZoneMatch.CENTRAL_ATTACK, matchDetail))
                .leftAttack(this.getCoefficientByPositionAndZone(player, position, ZoneMatch.LEFT_ATTACK, matchDetail))
                .build()));
    }

    private static double round(final double input) {
        final int value = (int) input;
        final double dec = input - value;
        if (0.0 < dec && dec <= 0.25) {
            return value + 0.25;
        }
        if (0.25 < dec && dec <= 0.5) {
            return value + 0.50;
        }
        if (0.5 < dec && dec <= 0.75) {
            return value + 0.75;
        }
        if (0.75 < dec) {
            return value + 1.0;
        }
        return value;
    }

    private static final Map<ZoneMatch, Map<Position, Map<Skill, Double>>> config = ImmutableMap.<ZoneMatch, Map<Position, Map<Skill, Double>>>builder()
            .put(ZoneMatch.RIGHT_DEFENSE, ImmutableMap.<Position, Map<Skill, Double>>builder()
                    .put(Position.KP, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.GOALKEEPING, 0.15555)
                            .put(Skill.DEFENDING, 0.06375)
                            .build())
                    .put(Position.MCD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.0663)
                            .build())
                    .put(Position.MCDO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.051000000000000004)
                            .build())
                    .put(Position.RCD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.1326)
                            .build())
                    .put(Position.RCDO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.10200000000000001)
                            .build())
                    .put(Position.RCDTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.20655)
                            .build())
                    .put(Position.RWB, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.2346)
                            .build())
                    .put(Position.RWBO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.1887)
                            .build())
                    .put(Position.RWBTM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.19125)
                            .build())
                    .put(Position.RWBD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.255)
                            .build())
                    .put(Position.MIM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.022949999999999998)
                            .build())
                    .put(Position.MIMO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.0102)
                            .build())
                    .put(Position.MIMD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.0357)
                            .build())
                    .put(Position.RIM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.04845)
                            .build())
                    .put(Position.RIMO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.022949999999999998)
                            .build())
                    .put(Position.RIMD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.06885000000000001)
                            .build())
                    .put(Position.RIMTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.0612)
                            .build())
                    .put(Position.RW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.08925)
                            .build())
                    .put(Position.RWO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.056100000000000004)
                            .build())
                    .put(Position.RWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.15555)
                            .build())
                    .put(Position.RWTM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.07395)
                            .build())
                    .build())
            .put(ZoneMatch.CENTRAL_DEFENSE, ImmutableMap.<Position, Map<Skill, Double>>builder()
                    .put(Position.KP, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.GOALKEEPING, 0.135333285)
                            .put(Skill.DEFENDING, 0.054444425000000005)
                            .build())
                    .put(Position.MCD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.1555555)
                            .build())
                    .put(Position.MCDO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.11355551500000001)
                            .build())
                    .put(Position.RCD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.1555555)
                            .build())
                    .put(Position.RCDO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.11355551500000001)
                            .build())
                    .put(Position.RCDTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.10422218500000001)
                            .build())
                    .put(Position.LCD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.1555555)
                            .build())
                    .put(Position.LCDO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.11355551500000001)
                            .build())
                    .put(Position.LCDTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.10422218500000001)
                            .build())
                    .put(Position.RWB, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.059111090000000005)
                            .build())
                    .put(Position.RWBO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.054444425000000005)
                            .build())
                    .put(Position.RWBTM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.10888885000000001)
                            .build())
                    .put(Position.RWBD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.066888865)
                            .build())
                    .put(Position.LWB, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.059111090000000005)
                            .build())
                    .put(Position.LWBO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.054444425000000005)
                            .build())
                    .put(Position.LWBTM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.10888885000000001)
                            .build())
                    .put(Position.LWBD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.066888865)
                            .build())
                    .put(Position.MIM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.062222200000000005)
                            .build())
                    .put(Position.MIMO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.024888880000000002)
                            .build())
                    .put(Position.MIMD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.09022219000000001)
                            .build())
                    .put(Position.RIM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.062222200000000005)
                            .build())
                    .put(Position.RIMO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.024888880000000002)
                            .build())
                    .put(Position.RIMD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.09022219000000001)
                            .build())
                    .put(Position.RIMTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.051333315000000004)
                            .build())
                    .put(Position.LIM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.062222200000000005)
                            .build())
                    .put(Position.LIMO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.024888880000000002)
                            .build())
                    .put(Position.LIMD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.09022219000000001)
                            .build())
                    .put(Position.LIMTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.051333315000000004)
                            .build())
                    .put(Position.RW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.031111100000000003)
                            .build())
                    .put(Position.RWO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.020222215)
                            .build())
                    .put(Position.RWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.038888875)
                            .build())
                    .put(Position.RWTM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.038888875)
                            .build())
                    .put(Position.LW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.031111100000000003)
                            .build())
                    .put(Position.LWO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.020222215)
                            .build())
                    .put(Position.LWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.038888875)
                            .build())
                    .put(Position.LWTM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.038888875)
                            .build())
                    .build())
            .put(ZoneMatch.LEFT_DEFENSE, ImmutableMap.<Position, Map<Skill, Double>>builder()
                    .put(Position.KP, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.GOALKEEPING, 0.15555)
                            .put(Skill.DEFENDING, 0.06375)
                            .build())
                    .put(Position.MCD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.1326 * 0.5)
                            .build())
                    .put(Position.MCDO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.10200000000000001 * 0.5)
                            .build())
                    .put(Position.LCD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.1326)
                            .build())
                    .put(Position.LCDO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.10200000000000001)
                            .build())
                    .put(Position.LCDTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.20655)
                            .build())
                    .put(Position.LWB, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.2346)
                            .build())
                    .put(Position.LWBO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.1887)
                            .build())
                    .put(Position.LWBTM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.19125)
                            .build())
                    .put(Position.LWBD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.255)
                            .build())
                    .put(Position.MIM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.04845 * 0.5)
                            .build())
                    .put(Position.MIMO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.022949999999999998 * 0.5)
                            .build())
                    .put(Position.MIMD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.06885000000000001 * 0.5)
                            .build())
                    .put(Position.LIM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.04845)
                            .build())
                    .put(Position.LIMO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.022949999999999998)
                            .build())
                    .put(Position.LIMD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.06885000000000001)
                            .build())
                    .put(Position.LIMTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.0612)
                            .build())
                    .put(Position.LW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.08925)
                            .build())
                    .put(Position.LWO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.056100000000000004)
                            .build())
                    .put(Position.LWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.15555)
                            .build())
                    .put(Position.LWTM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.DEFENDING, 0.07395)
                            .build())
                    .build())
            .put(ZoneMatch.MIDFIELD, ImmutableMap.<Position, Map<Skill, Double>>builder()
                    .put(Position.MCD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.02775)
                            .build())
                    .put(Position.MCDO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.0444)
                            .build())
                    .put(Position.RCD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.02775)
                            .build())
                    .put(Position.RCDO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.0444)
                            .build())
                    .put(Position.RCDTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.016649999999999998)
                            .build())
                    .put(Position.LCD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.02775)
                            .build())
                    .put(Position.LCDO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.0444)
                            .build())
                    .put(Position.LCDTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.016649999999999998)
                            .build())
                    .put(Position.RWB, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.016649999999999998)
                            .build())
                    .put(Position.RWBO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.0222)
                            .build())
                    .put(Position.RWBD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.0111)
                            .build())
                    .put(Position.RWBTM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.0222)
                            .build())
                    .put(Position.LWB, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.016649999999999998)
                            .build())
                    .put(Position.LWBO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.0222)
                            .build())
                    .put(Position.LWBD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.0111)
                            .build())
                    .put(Position.LWBTM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.0222)
                            .build())
                    .put(Position.MIM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.111)
                            .build())
                    .put(Position.MIMO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.10545)
                            .build())
                    .put(Position.MIMD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.10545)
                            .build())
                    .put(Position.RIM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.111)
                            .build())
                    .put(Position.RIMO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.10545)
                            .build())
                    .put(Position.RIMD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.10545)
                            .build())
                    .put(Position.RIMTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.0999)
                            .build())
                    .put(Position.LIM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.111)
                            .build())
                    .put(Position.LIMO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.10545)
                            .build())
                    .put(Position.LIMD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.10545)
                            .build())
                    .put(Position.LIMTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.0999)
                            .build())
                    .put(Position.RW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.04995)
                            .build())
                    .put(Position.RWO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.033299999999999996)
                            .build())
                    .put(Position.RWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.033299999999999996)
                            .build())
                    .put(Position.RWTM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.06105000000000001)
                            .build())
                    .put(Position.LW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.04995)
                            .build())
                    .put(Position.LWO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.033299999999999996)
                            .build())
                    .put(Position.LWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.033299999999999996)
                            .build())
                    .put(Position.LWTM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.06105000000000001)
                            .build())
                    .put(Position.MFW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.02775)
                            .build())
                    .put(Position.MFWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.038849999999999996)
                            .build())
                    .put(Position.RFW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.02775)
                            .build())
                    .put(Position.RFWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.038849999999999996)
                            .build())
                    .put(Position.RFWTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.016649999999999998)
                            .build())
                    .put(Position.LFW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.02775)
                            .build())
                    .put(Position.LFWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.038849999999999996)
                            .build())
                    .put(Position.LFWTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PLAY_MAKING, 0.016649999999999998)
                            .build())
                    .build())
            .put(ZoneMatch.RIGHT_ATTACK, ImmutableMap.<Position, Map<Skill, Double>>builder()
                    .put(Position.MIM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.02483)
                            .build())
                    .put(Position.MIMO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.03438)
                            .build())
                    .put(Position.MIMD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.013370000000000002)
                            .build())
                    .put(Position.MFW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.026740000000000003)
                            .put(Skill.WINGER, 0.04584)
                            .put(Skill.SCORING, 0.051570000000000005)
                            .build())
                    .put(Position.MFWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.05921)
                            .put(Skill.WINGER, 0.02483)
                            .put(Skill.SCORING, 0.02483)
                            .build())
                    .put(Position.RFW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.026740000000000003)
                            .put(Skill.WINGER, 0.04584)
                            .put(Skill.SCORING, 0.051570000000000005)
                            .build())
                    .put(Position.RFWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.05921)
                            .put(Skill.WINGER, 0.02483)
                            .put(Skill.SCORING, 0.02483)
                            .build())
                    .put(Position.LFW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.026740000000000003)
                            .put(Skill.WINGER, 0.04584)
                            .put(Skill.SCORING, 0.051570000000000005)
                            .build())
                    .put(Position.LFWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.05921)
                            .put(Skill.WINGER, 0.02483)
                            .put(Skill.SCORING, 0.02483)
                            .build())
                    .put(Position.RIM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.04966)
                            .build())
                    .put(Position.RIMO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.06876)
                            .build())
                    .put(Position.RIMD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.026740000000000003)
                            .build())
                    .put(Position.RIMTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.05921)
                            .put(Skill.WINGER, 0.05921)
                            .build())
                    .put(Position.RW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.04966)
                            .put(Skill.WINGER, 0.11269)
                            .build())
                    .put(Position.RWO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.055389999999999995)
                            .put(Skill.WINGER, 0.191)
                            .build())
                    .put(Position.RWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.04011)
                            .put(Skill.WINGER, 0.13179)
                            .build())
                    .put(Position.RWTM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.02865)
                            .put(Skill.WINGER, 0.14134)
                            .build())
                    .put(Position.RFWTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.04011)
                            .put(Skill.WINGER, 0.12224)
                            .put(Skill.SCORING, 0.09741)
                            .build())
                    .put(Position.LFWTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.01146)
                            .put(Skill.WINGER, 0.04011)
                            .put(Skill.SCORING, 0.03629)
                            .build())
                    .put(Position.RCDTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.WINGER, 0.04966)
                            .build())
                    .put(Position.RWB, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.WINGER, 0.11269)
                            .build())
                    .put(Position.RWBO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.WINGER, 0.13179)
                            .build())
                    .put(Position.RWBTM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.WINGER, 0.06684999999999999)
                            .build())
                    .put(Position.RWBD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.WINGER, 0.08595)
                            .build())
                    .build())
            .put(ZoneMatch.CENTRAL_ATTACK, ImmutableMap.<Position, Map<Skill, Double>>builder()
                    .put(Position.MIM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.0533775)
                            .put(Skill.SCORING, 0.035585)
                            .build())
                    .put(Position.MIMO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.0792575)
                            .put(Skill.SCORING, 0.0501425)
                            .build())
                    .put(Position.MIMD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.029115)
                            .put(Skill.SCORING, 0.0210275)
                            .build())
                    .put(Position.RIM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.0533775)
                            .put(Skill.SCORING, 0.035585)
                            .build())
                    .put(Position.RIMO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.0792575)
                            .put(Skill.SCORING, 0.0501425)
                            .build())
                    .put(Position.RIMD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.029115)
                            .put(Skill.SCORING, 0.0210275)
                            .build())
                    .put(Position.RIMTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.0372025)
                            .build())
                    .put(Position.LIM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.0533775)
                            .put(Skill.SCORING, 0.035585)
                            .build())
                    .put(Position.LIMO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.0792575)
                            .put(Skill.SCORING, 0.0501425)
                            .build())
                    .put(Position.LIMD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.029115)
                            .put(Skill.SCORING, 0.0210275)
                            .build())
                    .put(Position.LIMTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.0372025)
                            .build())
                    .put(Position.RW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.0177925)
                            .build())
                    .put(Position.RWO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.0210275)
                            .build())
                    .put(Position.RWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.008087500000000001)
                            .build())
                    .put(Position.RWTM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.02588)
                            .build())
                    .put(Position.LW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.0177925)
                            .build())
                    .put(Position.LWO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.0210275)
                            .build())
                    .put(Position.LWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.008087500000000001)
                            .build())
                    .put(Position.LWTM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.02588)
                            .build())
                    .put(Position.MFW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.0533775)
                            .put(Skill.SCORING, 0.16175)
                            .build())
                    .put(Position.MFWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.08572750000000001)
                            .put(Skill.SCORING, 0.09058000000000001)
                            .build())
                    .put(Position.RFW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.0533775)
                            .put(Skill.SCORING, 0.16175)
                            .build())
                    .put(Position.RFWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.08572750000000001)
                            .put(Skill.SCORING, 0.09058000000000001)
                            .build())
                    .put(Position.RFWTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.0372025)
                            .put(Skill.SCORING, 0.106755)
                            .build())
                    .put(Position.LFW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.0533775)
                            .put(Skill.SCORING, 0.16175)
                            .build())
                    .put(Position.LFWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.08572750000000001)
                            .put(Skill.SCORING, 0.09058000000000001)
                            .build())
                    .put(Position.LFWTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.0372025)
                            .put(Skill.SCORING, 0.106755)
                            .build())
                    .build())
            .put(ZoneMatch.LEFT_ATTACK, ImmutableMap.<Position, Map<Skill, Double>>builder()
                    .put(Position.MIM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.02483)
                            .build())
                    .put(Position.MIMO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.03438)
                            .build())
                    .put(Position.MIMD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.013370000000000002)
                            .build())
                    .put(Position.MFW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.026740000000000003)
                            .put(Skill.WINGER, 0.04584)
                            .put(Skill.SCORING, 0.051570000000000005)
                            .build())
                    .put(Position.MFWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.05921)
                            .put(Skill.WINGER, 0.02483)
                            .put(Skill.SCORING, 0.02483)
                            .build())
                    .put(Position.LFW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.026740000000000003)
                            .put(Skill.WINGER, 0.04584)
                            .put(Skill.SCORING, 0.051570000000000005)
                            .build())
                    .put(Position.LFWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.05921)
                            .put(Skill.WINGER, 0.02483)
                            .put(Skill.SCORING, 0.02483)
                            .build())
                    .put(Position.RFW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.026740000000000003)
                            .put(Skill.WINGER, 0.04584)
                            .put(Skill.SCORING, 0.051570000000000005)
                            .build())
                    .put(Position.RFWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.05921)
                            .put(Skill.WINGER, 0.02483)
                            .put(Skill.SCORING, 0.02483)
                            .build())
                    .put(Position.LIM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.04966)
                            .build())
                    .put(Position.LIMO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.06876)
                            .build())
                    .put(Position.LIMD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.026740000000000003)
                            .build())
                    .put(Position.LIMTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.05921)
                            .put(Skill.WINGER, 0.05921)
                            .build())
                    .put(Position.LW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.04966)
                            .put(Skill.WINGER, 0.11269)
                            .build())
                    .put(Position.LWO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.055389999999999995)
                            .put(Skill.WINGER, 0.191)
                            .build())
                    .put(Position.LWD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.04011)
                            .put(Skill.WINGER, 0.13179)
                            .build())
                    .put(Position.LWTM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.02865)
                            .put(Skill.WINGER, 0.14134)
                            .build())
                    .put(Position.LFWTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.04011)
                            .put(Skill.WINGER, 0.12224)
                            .put(Skill.SCORING, 0.09741)
                            .build())
                    .put(Position.RFWTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.PASSING, 0.01146)
                            .put(Skill.WINGER, 0.04011)
                            .put(Skill.SCORING, 0.03629)
                            .build())
                    .put(Position.LCDTW, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.WINGER, 0.04966)
                            .build())
                    .put(Position.LWB, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.WINGER, 0.11269)
                            .build())
                    .put(Position.LWBO, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.WINGER, 0.13179)
                            .build())
                    .put(Position.LWBTM, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.WINGER, 0.06684999999999999)
                            .build())
                    .put(Position.LWBD, ImmutableMap.<Skill, Double>builder()
                            .put(Skill.WINGER, 0.08595)
                            .build())
                    .build())
            .build();

    private double getCoefficientByPositionAndZone(final Player player, final Position position, final ZoneMatch zone, final MatchDetail matchDetail) {
        double c;
        try {
            c = config.get(zone).get(position).entrySet().stream().mapToDouble(e -> this.getEffectiveSkill(player, e.getKey()) * e.getValue()).sum();
            if (player.getSpecialty() == Specialty.TECHNICAL && ((zone == ZoneMatch.RIGHT_ATTACK) || (zone == ZoneMatch.LEFT_ATTACK)) && ((position == Position.MFWD) || (position == Position.RFWD) || (position == Position.LFWD))) {
                c += this.getEffectiveSkill(player, Skill.PASSING) * 0.0191;
            }
        } catch (final Exception e) {
            c = 0;
        }
        //return round(this.applyCommonProps(c, zone, matchDetail));
        return this.applyCommonProps(c, zone, matchDetail);
    }

    private double applyCommonProps(final double inVal, final ZoneMatch zone, final MatchDetail matchDetail) {
        double retVal = inVal;
        //retVal += props.getOrDefault(squareMod, 0.0) * Math.pow(retVal, 2);
        //retVal += props.getOrDefault(cubeMod, 0.0) * Math.pow(retVal, 3);
        //retVal *= props.getOrDefault(matchDetail.getTactic().getProp(), 1.0);
        if (zone == ZoneMatch.MIDFIELD) {
            final double teamSpirit = matchDetail.getTeamSpirit().getValue() + matchDetail.getTeamSubSpirit();
            retVal *= Math.pow(teamSpirit * 0.147832, 0.417779);
            retVal *= matchDetail.getSideMatch().getFactor();
            retVal *= matchDetail.getTeamAttitude().getFactor();
        }
        if (zone.getLine() == LineMatch.ATTACK) {
            retVal *= (1.0 + 0.0525 * (matchDetail.getTeamConfidence().getValue() - 5));
        }

        final double offensive = zone.getLine().getTrainerOffensiveFactor();
        final double defensive = zone.getLine().getTrainerDefensiveFactor();
        final double outlier = matchDetail.getStyleOfPlay() >= 0 ? offensive : defensive;
        retVal *= 1.0 + (Math.abs(matchDetail.getStyleOfPlay()) * 0.01) * (outlier - 1.0);

        //retVal = Math.pow(retVal, 1.165);
        //retVal += 0.75;
        return retVal;
    }

    private double getEffectiveSkill(final Player player, final Skill skill) {
        double form = player.getForm();
        double value = player.getSkill(skill) + this.getLoyaltyHomegrownBonus(player);
        final double xp = (4.0 / 3.0) * Math.log10(player.getExperience());
        value += xp;
        form = Math.max(form, 1.0);
        form = Math.min(form, 8.0);
        form *= 0.125;
        form = Math.pow(form, 2.0 / 3.0);
        return value * form;
    }

    private double getLoyaltyHomegrownBonus(final Player player) {
        return player.isMotherClubBonus() ? 1.5 : (player.getLoyalty() - 1) / 19.0;
    }

}
