package net.ddns.tiojack.htte.model;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

import java.util.List;

import static net.ddns.tiojack.htte.model.RoleGroup.BACK;
import static net.ddns.tiojack.htte.model.RoleGroup.CENTRAL_DEFENDER;
import static net.ddns.tiojack.htte.model.RoleGroup.FORWARD;
import static net.ddns.tiojack.htte.model.RoleGroup.INNER_MIDFIELD;
import static net.ddns.tiojack.htte.model.RoleGroup.KEEPER;
import static net.ddns.tiojack.htte.model.RoleGroup.WINGER;

@Getter
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public enum Formation {
    F_5_5_0_A("5-5-0", 1, 2, 3, 3, 2, 0, List.of(KEEPER, BACK, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, WINGER)),
    F_5_4_1_A("5-4-1", 1, 2, 3, 2, 2, 1, List.of(KEEPER, BACK, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, WINGER, FORWARD)),
    F_5_4_1_B("5-4-1", 1, 2, 3, 3, 1, 1, List.of(KEEPER, BACK, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, FORWARD)),
    F_5_3_2_A("5-3-2", 1, 2, 3, 1, 2, 2, List.of(KEEPER, BACK, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, WINGER, WINGER, FORWARD, FORWARD)),
    F_5_3_2_B("5-3-2", 1, 2, 3, 2, 1, 2, List.of(KEEPER, BACK, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, FORWARD, FORWARD)),
    F_5_3_2_C("5-3-2", 1, 2, 3, 3, 0, 2, List.of(KEEPER, BACK, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, INNER_MIDFIELD, FORWARD, FORWARD)),
    F_5_2_3_A("5-2-3", 1, 2, 3, 0, 2, 3, List.of(KEEPER, BACK, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, WINGER, WINGER, FORWARD, FORWARD, FORWARD)),
    F_5_2_3_B("5-2-3", 1, 2, 3, 1, 1, 3, List.of(KEEPER, BACK, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, WINGER, FORWARD, FORWARD, FORWARD)),
    F_5_2_3_C("5-2-3", 1, 2, 3, 2, 0, 3, List.of(KEEPER, BACK, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, FORWARD, FORWARD, FORWARD)),
    F_4_5_1_A("4-5-1", 1, 2, 2, 3, 2, 1, List.of(KEEPER, BACK, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, WINGER, FORWARD)),
    F_4_5_1_B("4-5-1", 1, 1, 3, 3, 2, 1, List.of(KEEPER, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, WINGER, FORWARD)),
    F_4_4_2_A("4-4-2", 1, 2, 2, 2, 2, 2, List.of(KEEPER, BACK, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, WINGER, FORWARD, FORWARD)),
    F_4_4_2_B("4-4-2", 1, 2, 2, 3, 1, 2, List.of(KEEPER, BACK, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, FORWARD, FORWARD)),
    F_4_4_2_C("4-4-2", 1, 1, 3, 2, 2, 2, List.of(KEEPER, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, WINGER, FORWARD, FORWARD)),
    F_4_4_2_D("4-4-2", 1, 1, 3, 3, 1, 2, List.of(KEEPER, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, FORWARD, FORWARD)),
    F_4_3_3_A("4-3-3", 1, 2, 2, 1, 2, 3, List.of(KEEPER, BACK, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, WINGER, WINGER, FORWARD, FORWARD, FORWARD)),
    F_4_3_3_B("4-3-3", 1, 2, 2, 2, 1, 3, List.of(KEEPER, BACK, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, FORWARD, FORWARD, FORWARD)),
    F_4_3_3_C("4-3-3", 1, 2, 2, 3, 0, 3, List.of(KEEPER, BACK, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, INNER_MIDFIELD, FORWARD, FORWARD, FORWARD)),
    F_4_3_3_D("4-3-3", 1, 1, 3, 1, 2, 3, List.of(KEEPER, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, WINGER, WINGER, FORWARD, FORWARD, FORWARD)),
    F_4_3_3_E("4-3-3", 1, 1, 3, 2, 1, 3, List.of(KEEPER, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, FORWARD, FORWARD, FORWARD)),
    F_4_3_3_F("4-3-3", 1, 1, 3, 3, 0, 3, List.of(KEEPER, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, INNER_MIDFIELD, FORWARD, FORWARD, FORWARD)),
    F_3_5_2_A("3-5-2", 1, 2, 1, 3, 2, 2, List.of(KEEPER, BACK, BACK, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, WINGER, FORWARD, FORWARD)),
    F_3_5_2_B("3-5-2", 1, 1, 2, 3, 2, 2, List.of(KEEPER, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, WINGER, FORWARD, FORWARD)),
    F_3_5_2_C("3-5-2", 1, 0, 3, 3, 2, 2, List.of(KEEPER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, WINGER, FORWARD, FORWARD)),
    F_3_4_3_A("3-4-3", 1, 2, 1, 2, 2, 3, List.of(KEEPER, BACK, BACK, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, WINGER, FORWARD, FORWARD, FORWARD)),
    F_3_4_3_B("3-4-3", 1, 2, 1, 3, 1, 3, List.of(KEEPER, BACK, BACK, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, FORWARD, FORWARD, FORWARD)),
    F_3_4_3_C("3-4-3", 1, 1, 2, 2, 2, 3, List.of(KEEPER, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, WINGER, FORWARD, FORWARD, FORWARD)),
    F_3_4_3_D("3-4-3", 1, 1, 2, 3, 1, 3, List.of(KEEPER, BACK, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, FORWARD, FORWARD, FORWARD)),
    F_3_4_3_E("3-4-3", 1, 0, 3, 2, 2, 3, List.of(KEEPER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, WINGER, FORWARD, FORWARD, FORWARD)),
    F_3_4_3_F("3-4-3", 1, 0, 3, 3, 1, 3, List.of(KEEPER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, FORWARD, FORWARD, FORWARD)),
    F_2_5_3_A("2-5-3", 1, 2, 0, 3, 2, 3, List.of(KEEPER, BACK, BACK, INNER_MIDFIELD, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, WINGER, FORWARD, FORWARD, FORWARD)),
    F_2_5_3_B("2-5-3", 1, 1, 1, 3, 2, 3, List.of(KEEPER, BACK, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, WINGER, FORWARD, FORWARD, FORWARD)),
    F_2_5_3_C("2-5-3", 1, 0, 2, 3, 2, 3, List.of(KEEPER, CENTRAL_DEFENDER, CENTRAL_DEFENDER, INNER_MIDFIELD, INNER_MIDFIELD, INNER_MIDFIELD, WINGER, WINGER, FORWARD, FORWARD, FORWARD));

    private final String name;
    private final int numGK;
    private final int numWB;
    private final int numCD;
    private final int numIM;
    private final int numWI;
    private final int numFW;
    private final List<RoleGroup> roleGroups;

}
